# Generated by Django 5.2 on 2025-05-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(db_index=True, max_length=225),
        ),
    ]
